# Generated by Django 3.2.8 on 2021-10-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='artical',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='anons'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
